name: Nightly checks

# runs every day at midnight
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test_storybook_prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Upgrade to storybook@next
        run: |
          npx storybook upgrade --prerelease

      - name: Run test runner
        run: |
          yarn build
          yarn test-storybook:ci

      - name: Get prerelease version of Storybook
        if: ${{ failure() }}
        run: |
          echo "sb_version=$(npm view @storybook/react@prerelease version)" >> $GITHUB_ENV
      
      - name: Report incoming errors
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID }}"
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":storybook: :runner: [Test Runner] The Nightly check has failed :alert:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Storybook version:*\n${{ env.sb_version }}"
                    }
                  ],
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View failure",
                      "emoji": true
                    },
                    "value": "view_failure",
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
